### ISSUE TITLE
Error while running in Jetbrain after downloaded

### ISSUE THREAD

**Issue by samrawi** [oroinc/oro-phpstorm-plugin#19]
com.intellij.diagnostic.PluginException: Cannot create extension (class=com.oroplatform.idea.oroplatform.intellij.indexes.OperationFileBasedIndex) [Plugin: com.oroplatform.idea.oroplatform]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:931)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:88)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:461)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.access$200(ExtensionPointImpl.java:33)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl$1.next(ExtensionPointImpl.java:369)
	at com.intellij.util.indexing.FileBasedIndexDataInitialization.initAssociatedDataForExtensions(FileBasedIndexDataInitialization.java:70)
	at com.intellij.util.indexing.FileBasedIndexDataInitialization.prepareTasks(FileBasedIndexDataInitialization.java:111)
	at com.intellij.util.indexing.IndexDataInitializer.call(IndexDataInitializer.kt:20)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:246)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:32)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:225)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:214)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.intellij.diagnostic.PluginException: Cannot create class com.oroplatform.idea.oroplatform.intellij.indexes.OperationFileBasedIndex (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Oro PHPStorm Plugin, id=com.oroplatform.idea.oroplatform, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2021.3\plugins\idea-oroplatform-plugin, version=1.0.19, package=null, isBundled=false), packagePrefix=null, instanceId=164, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:869)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.instantiateClass(XmlExtensionAdapter.java:99)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:116)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:66)
	... 19 more
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:482)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:830)
	... 22 more
Caused by: java.lang.RuntimeException: java.nio.file.FileSystemException: C:\Users\Administrator\AppData\Local\JetBrains\IntelliJIdea2021.3\index\indices.enum: The requested operation cannot be performed on a file with a user-mapped section open.

	at com.intellij.util.io.SimpleStringPersistentEnumerator.writeStorageToDisk(SimpleStringPersistentEnumerator.java:113)
	at com.intellij.util.io.SimpleStringPersistentEnumerator.enumerate(SimpleStringPersistentEnumerator.java:50)
	at com.intellij.util.indexing.ID.stringToId(ID.java:56)
	at com.intellij.util.indexing.ID.findByName(ID.java:81)
	at com.intellij.util.indexing.ID.create(ID.java:66)
	at com.oroplatform.idea.oroplatform.intellij.indexes.OperationFileBasedIndex.<clinit>(OperationFileBasedIndex.java:9)
	... 25 more
Caused by: java.nio.file.FileSystemException: C:\Users\Administrator\AppData\Local\JetBrains\IntelliJIdea2021.3\index\indices.enum: The requested operation cannot be performed on a file with a user-mapped section open.

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:239)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
	at java.base/java.nio.file.Files.write(Files.java:3565)
	at com.intellij.util.io.SimpleStringPersistentEnumerator.writeStorageToDisk(SimpleStringPersistentEnumerator.java:110)
	... 30 more

**Comment by mbessolov** [comment]
I was not able to reproduce this issue.
If you are still experiencing problem with the plugin, feel free to reopen or report a new issue - please make sure to specify the exact version of PhpStorm (you can find it in the About window) and the version of the Oro plugin.
